export const channels = Object.freeze({
  getState: "chroma:get-state",
  smokeViewports: "chroma:smoke-viewports",
  stateChanged: "chroma:state-changed",
  layoutChanged: "chroma:layout-changed",
  sidebarOverlayChanged: "chroma:sidebar-overlay-changed",
  chromeModalChanged: "chroma:chrome-modal-changed",
  tabDragChanged: "chroma:tab-drag-changed",
  splitRatioPreview: "chroma:split-ratio-preview",
  windowDragStart: "chroma:window-drag-start",
  windowDragMove: "chroma:window-drag-move",
  windowDragEnd: "chroma:window-drag-end",
  windowControl: "chroma:window-control",
  openHistory: "chroma:open-history",
  openCommandPalette: "chroma:open-command-palette",
  invoke: "chroma:invoke",
});

export const commands = Object.freeze({
  createTab: "tab:create",
  selectTab: "tab:select",
  closeTab: "tab:close",
  reopenTab: "tab:reopen",
  reorderTab: "tab:reorder",
  navigate: "navigation:go",
  back: "navigation:back",
  forward: "navigation:forward",
  reload: "navigation:reload",
  stop: "navigation:stop",
  toggleMute: "tab:toggle-mute",
  togglePin: "tab:toggle-pin",
  toggleEssential: "tab:toggle-essential",
  toggleBookmark: "bookmark:toggle",
  removeBookmark: "bookmark:remove",
  queryHistory: "history:query",
  suggestHistory: "history:suggest",
  removeHistory: "history:remove",
  clearHistory: "history:clear",
  setHistoryPreferences: "history:set-preferences",
  openHistory: "history:open",
  pauseDownload: "download:pause",
  resumeDownload: "download:resume",
  cancelDownload: "download:cancel",
  openDownload: "download:open",
  revealDownload: "download:reveal",
  removeDownload: "download:remove",
  clearDownloads: "download:clear-finished",
  createWorkspace: "workspace:create",
  selectWorkspace: "workspace:select",
  renameWorkspace: "workspace:rename",
  splitActive: "split:active",
  splitTabs: "split:tabs",
  detachSplitTab: "split:detach",
  unsplitActive: "split:remove",
  setSplitRatio: "split:set-ratio",
  createFolder: "folder:create",
  toggleFolder: "folder:toggle",
  renameFolder: "folder:rename",
  deleteFolder: "folder:delete",
  toggleSidebar: "sidebar:toggle",
  setSidebarWidth: "sidebar:set-width",
  setAppearance: "settings:set-appearance",
  openDevTools: "developer:open-tools",
});

export const commandNames = new Set(Object.values(commands));
